### ISSUE TITLE
World transfer problem

### ISSUE THREAD

**Issue by CarlderWal** [TheRemote/RaspberryPiMinecraft#29]
Hi 
i have an issuing with Transferring a world to a new Minecraft server instance.
[first excuse my englisch]
I got the api v1/v2 bug and fixed it with a new installation.
But now I have the Problem that if I am copying an world (made on this server before) (everything in 1.17.1)to the new installation it starts (sometimes I have to agree the Eula in Eula.tx) but on the second start it resets the Eula to false and delete start.sh/stop.sh and many other important scripts. I tried to set the file permission to only read from the Eula but it resets after one or two reboots/restarts of the server.

The strange thing is that with the normal installation it won't happen(if I doesn't import the world)

I hope you can help me and Thanks in advance

**Comment by TheRemote** [comment]
Hello,

Whenever we've seen this it's due to not using the default installation path (leaving it as ~).  Are you happening to be typing in an installation path of ~/minecraft or something like that?  That would definitely cause this behavior.  The path it is asking for is the root installation path and it will make the minecraft folder itself.  If you're typing in a non-root path it will prune the folder which is why files are disappearing and why I'm pretty sure this is what is going on.

Can you try installing using the normal path ~ and then importing your backup into there?

**Comment by CarlderWal** [comment]
I ever used the normal location /home/pi/ and I tried although ~
The problem although happens with a new generated world (I described it false in my last entry)
The Eula resets itself after a few reboots 
(and im using the normal pi user)

**Comment by CarlderWal** [comment]
[Dateien-2.zip](https://github.com/TheRemote/RaspberryPiMinecraft/files/7628548/Dateien-2.zip)
I can't make any backup because I have to restart the server. here are my files (without paperclip.jar and world data because they are to big))

**Comment by CarlderWal** [comment]
> Hello,
> 
> Whenever we've seen this it's due to not using the default installation path (leaving it as ~). Are you happening to be typing in an installation path of ~/minecraft or something like that? That would definitely cause this behavior. The path it is asking for is the root installation path and it will make the minecraft folder itself. If you're typing in a non-root path it will prune the folder which is why files are disappearing and why I'm pretty sure this is what is going on.
> 
> Can you try installing using the normal path ~ and then importing your backup into there?

i set up an complete new version with default path and new raspbian and it didn't worked as well
