### ISSUE TITLE
Unable to Set Path Variable - restart.sh

### ISSUE THREAD

**Issue by jmsuan** [TheRemote/RaspberryPiMinecraft#37]
![image](https://user-images.githubusercontent.com/73461052/167299922-916f95dc-6294-4379-829d-9f2bfcc7aab8.png)
Error is thrown every time restart.sh is run. Every fresh installation I've had has had this error so far, I've made sure my Pi is up to date every time too.

100% Reproducible on Pi 4 (8gb) when using Raspberry Pi OS Lite (64bit), booting from USB drive. (I believe it happened too with booting from SD card.) I can provide additional details if requested, thanks. I only access the system through SSH but I doubt that would be related.

**Comment by TheRemote** [comment]
Well that is certainly unexpected.  It usually means you don't have bash installed.  I've never seen or heard of that on Raspberry Pi OS.  Maybe they are changing away from bash like so many other flavors have already done?

Actually I see a different problem in here.  It's only in restart.sh and at the top of the file it has:

`#!/bin/sh`

instead of:

`#!/bin/bash`

It probably actually is running it with the POSIX shell that doesn't support a double [[.  I'm going to upload a fix for this.  Can you run SetupMinecraft.sh again and make sure this isn't happening?  Thank you for reporting this!

**Comment by jmsuan** [comment]
Looks like that fixed this issue.

Thank you for your generous contributions including this project. It's been a life saver!

**Comment by TheRemote** [comment]
Thank you very much again for reporting it, I'm glad that took care of it!

I never cease to be humbled by the projects.  You'd think that since I still regularly run and play on the server that I would have seen all of these but the truth is the developers often if not usually don't see it in their development environment.

This is why I'm a big believer in open source.  I'm glad to be participating in the community and glad you are here as well.  Take care!
