### ISSUE TITLE
Update for 1.19 version

### ISSUE THREAD

**Issue by pipidaxian** [TheRemote/RaspberryPiMinecraft#40]
The client version now is 1.19, but the latest server version is still 1.18.2. When I set the installation version to 1.19, the game crashed after launch. So how and when can I have the latest version on my server? 
Thanks a lot.

**Comment by TheRemote** [comment]
Hey pipidaxian,

This runs the Paper Minecraft server which has their download page at https://papermc.io/downloads#Paper-1.19

Basically what is wrong is that 1.19 doesn't exist yet for Paper.  It hasn't been released.  It's crashing because there's no download available.

It usually takes them a day or two after a release to get something out so I'd expect it to come out today or tomorrow most likely!

**Comment by pipidaxian** [comment]
I see, I just need to wait, thanks

**Comment by TheRemote** [comment]
No worries at all!  I've got the page up that I'm refreshing periodically throughout the day.  If you see that it has dropped on that page before I do you can do exactly what you've been doing with the version override and it will work (it just needs to exist on the servers first).

Take care!
